### ISSUE TITLE
大神能指点下怎么启动项目吗

### ISSUE THREAD

**Issue by dengchao789** [CN-GuoZiyang/MYDB#2]
The goal you specified requires a project to execute but there is no POM in this directory (C:\Users\DC0426\IdeaProjects\MYDB-master). Please verify you invoked Maven from the correct directory. 
额，大神这项目怎么启动来着。。。。。。小白试了你的方法不行。。。。。。。。

**Comment by CN-GuoZiyang** [comment]
先跑一遍mvn install

**Comment by dengchao789** [comment]
> 先跑一遍mvn install

好的，我试试，谢谢大神指点

**Comment by BossCclHungry** [comment]
大神能详细教教怎么启动嘛，真就是启动不了啊，编译正常通过。接下来就提示[ERROR] Unknown lifecycle phase ".mainClass=top.guoziyang.mydb.backend.Launcher". 这个了
