### ISSUE TITLE
请问您有遇到过这个报错嘛？

### ISSUE THREAD

**Issue by oldwang77** [CN-GuoZiyang/MYDB#3]
Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (default-cli) on project MyDB: An exception occured while executing the Java class. top.guoziyang.mydb.backend.Launcher -> [Help 1]

**Comment by oldwang77** [comment]
解决了谢谢

**Comment by LaiJian0825** [comment]
请问怎么解决的

**Comment by LaiJian0825** [comment]
请问怎么解决的

**Comment by liyijuan** [comment]
① 命令行编译运行
![image](https://user-images.githubusercontent.com/68106875/215394893-0a933fc3-6a1e-4713-936a-eded22e91f2a.png)

② IDEA 编译运行
![image](https://user-images.githubusercontent.com/68106875/215395324-5fa2c84a-8914-4ea3-9f5e-36625b850bf2.png)
